/***************************************************************************
 *                                                                         *
 *   wb_serial_port.v - Wishbone bus connected RS-232 type serial port.    *
 *                                                                         *
 *   Copyright (C) 2009 by Patrick Suggate                                 *
 *   patrick@physics.otago.ac.nz                                           *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

// `define __use_random

`timescale 1ns/100ps
module wb_serial_port #(
	parameter	HIGHZ	= 0,
	parameter	WIDTH	= 8,
	parameter	DIVIDER	= 123456,
	parameter	ENABLES	= WIDTH / 8,
	parameter	MSB	= WIDTH - 1,
	parameter	ESB	= ENABLES - 1
) (
	input		wb_clk_i,
	input		wb_rst_i,
	
	input		wb_cyc_i,
	input		wb_stb_i,
	input		wb_we_i,
	output		wb_ack_o,
	output		wb_rty_o,
	output		wb_err_o,
	input	[ESB:0]	wb_sel_i,
	input	[MSB:0]	wb_dat_i,
	output	[ESB:0]	wb_sel_o,
	output	[MSB:0]	wb_dat_o,
	
	output		sp_clk_o,
	output		sp_tx_o,
	input		sp_rx_i
);

reg	ack	= 0;
reg	[MSB:0]	dat	= 0;


assign	leds_o	= dat[LSB:0];

assign	#2 wb_ack_o	= HIGHZ ? (ack ? 1'b1 : 'bz) : ack ;
assign	#2 wb_rty_o	= HIGHZ ? (ack ? 0 : 'bz) : 0 ;
assign	#2 wb_err_o	= HIGHZ ? (ack ? 0 : 'bz) : 0 ;
assign	#2 wb_sel_o	= HIGHZ ? (ack ? {ENABLES{ack}} : 'bz) : {ENABLES{ack}} ;
assign	#2 wb_dat_o	= HIGHZ ? (ack ? dat : 'bz) : dat ;


always @(posedge wb_clk_i)
	if (wb_rst_i)
		ack	<= #2 0;
	else if (wb_cyc_i && wb_stb_i && !ack)
		ack	<= #2 1;
	else
		ack	<= #2 0;


// TODO: Byte-enables
always @(posedge wb_clk_i)
	if (wb_rst_i)	dat	<= #2 0;
	else if (wb_cyc_i && wb_stb_i && wb_we_i) begin
`ifdef __use_random
		dat	<= #2 $random;
`else
 		dat	<= #2 wb_dat_i;
`endif
	end

// Instantiate Jeung Joon Lee's Micro-UART. This UART uses less than 55
// flip-flops, and less than 2% of a Xilinx 200K gate Spartan III FPGA.
// The include file for this UART specifies the divider to be used to
// generate the UART clock from the system clock.
uart UART0(
	.sys_clk	(wb_clk_i),	// 50 MHz from the Spartan III board
	.sys_rst_l	(~wb_rst_i),	// Reset when low
	.uart_clk	(uart_clk),	// Generated by the UART, 16 * baud
	
	.uart_XMIT_dataH(sp_tx_o),	// Transmitter pins
	.xmitH		(data_send),
	.xmit_dataH	(data_out),
	.xmit_doneH	(tx_done),
	
	.uart_REC_dataH	(sp_rx_i), 	// Receive pins
	.rec_dataH	(data_in),
	.rec_readyH	(rx_ready)
);


endmodule	// wb_serial_port
